// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKQ2-bjf5U7QgWWUkWkH2YhEPsWURFeII',
    appId: '1:188701911900:web:912404168256e0ddc46f99',
    messagingSenderId: '188701911900',
    projectId: 'demonotification-5aa2b',
    authDomain: 'demonotification-5aa2b.firebaseapp.com',
    storageBucket: 'demonotification-5aa2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgUn4vd6jKlPNH3upvUMlS09LX5ZpTIaE',
    appId: '1:188701911900:android:83489dd7c2ebcc39c46f99',
    messagingSenderId: '188701911900',
    projectId: 'demonotification-5aa2b',
    storageBucket: 'demonotification-5aa2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYPqYnpjWbvNUHP8WJ2dO5z9p3Q-LvTCU',
    appId: '1:188701911900:ios:84e0a54d6b7b7b09c46f99',
    messagingSenderId: '188701911900',
    projectId: 'demonotification-5aa2b',
    storageBucket: 'demonotification-5aa2b.appspot.com',
    iosBundleId: 'com.example.messagerdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYPqYnpjWbvNUHP8WJ2dO5z9p3Q-LvTCU',
    appId: '1:188701911900:ios:84e0a54d6b7b7b09c46f99',
    messagingSenderId: '188701911900',
    projectId: 'demonotification-5aa2b',
    storageBucket: 'demonotification-5aa2b.appspot.com',
    iosBundleId: 'com.example.messagerdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKQ2-bjf5U7QgWWUkWkH2YhEPsWURFeII',
    appId: '1:188701911900:web:084c883b14c60254c46f99',
    messagingSenderId: '188701911900',
    projectId: 'demonotification-5aa2b',
    authDomain: 'demonotification-5aa2b.firebaseapp.com',
    storageBucket: 'demonotification-5aa2b.appspot.com',
  );
}
